title: The Stack Trace
description: >-
  feed your brain
lang: it
author: Ludovico
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: true

# Analytics - Goatcounter (cambia con il tuo codice)
goatcounter: the-stack-trace